//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colorado.Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Colorado.Viewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude angle.
        /// </summary>
        public static string AltitudeAngleText {
            get {
                return ResourceManager.GetString("AltitudeAngleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string AppearanceTabHeader {
            get {
                return ResourceManager.GetString("AppearanceTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azimuth angle.
        /// </summary>
        public static string AzimuthAngleText {
            get {
                return ResourceManager.GetString("AzimuthAngleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color settings:.
        /// </summary>
        public static string BackgroundColorSettings {
            get {
                return ResourceManager.GetString("BackgroundColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default materials:.
        /// </summary>
        public static string DefaultMaterials {
            get {
                return ResourceManager.GetString("DefaultMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable lighting.
        /// </summary>
        public static string EnableLightingCheckBoxText {
            get {
                return ResourceManager.GetString("EnableLightingCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global material settings.
        /// </summary>
        public static string GlobalMaterialSettings {
            get {
                return ResourceManager.GetString("GlobalMaterialSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient:.
        /// </summary>
        public static string LightAmbientColor {
            get {
                return ResourceManager.GetString("LightAmbientColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color settings:.
        /// </summary>
        public static string LightColorSettings {
            get {
                return ResourceManager.GetString("LightColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diffuse:.
        /// </summary>
        public static string LightDiffuseColor {
            get {
                return ResourceManager.GetString("LightDiffuseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting settings.
        /// </summary>
        public static string LightingExpanderHeader {
            get {
                return ResourceManager.GetString("LightingExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting.
        /// </summary>
        public static string LightingTabHeader {
            get {
                return ResourceManager.GetString("LightingTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position settings:.
        /// </summary>
        public static string LightPositionSettings {
            get {
                return ResourceManager.GetString("LightPositionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specular:.
        /// </summary>
        public static string LightSpecularColor {
            get {
                return ResourceManager.GetString("LightSpecularColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient:.
        /// </summary>
        public static string MaterialAmbientColor {
            get {
                return ResourceManager.GetString("MaterialAmbientColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diffuse:.
        /// </summary>
        public static string MaterialDiffuseColor {
            get {
                return ResourceManager.GetString("MaterialDiffuseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emission:.
        /// </summary>
        public static string MaterialEmissionColor {
            get {
                return ResourceManager.GetString("MaterialEmissionColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material settings.
        /// </summary>
        public static string MaterialExpanderHeader {
            get {
                return ResourceManager.GetString("MaterialExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specular:.
        /// </summary>
        public static string MaterialSpecularColor {
            get {
                return ResourceManager.GetString("MaterialSpecularColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string MaterialTabHeader {
            get {
                return ResourceManager.GetString("MaterialTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering.
        /// </summary>
        public static string RenderingTabHeader {
            get {
                return ResourceManager.GetString("RenderingTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shininess radius:.
        /// </summary>
        public static string Shininess {
            get {
                return ResourceManager.GetString("Shininess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception has been occurred. The application will be terminated.
        /// </summary>
        public static string UnhandledExceptionOccured {
            get {
                return ResourceManager.GetString("UnhandledExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use global material.
        /// </summary>
        public static string UseGlobalMaterial {
            get {
                return ResourceManager.GetString("UseGlobalMaterial", resourceCulture);
            }
        }
    }
}
