//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colorado.Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Colorado.Viewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude angle.
        /// </summary>
        public static string AltitudeAngleText {
            get {
                return ResourceManager.GetString("AltitudeAngleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string AppearanceTabHeader {
            get {
                return ResourceManager.GetString("AppearanceTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azimuth angle.
        /// </summary>
        public static string AzimuthAngleText {
            get {
                return ResourceManager.GetString("AzimuthAngleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color settings:.
        /// </summary>
        public static string BackgroundColorSettings {
            get {
                return ResourceManager.GetString("BackgroundColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All.
        /// </summary>
        public static string CloseAll {
            get {
                return ResourceManager.GetString("CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate system axes length.
        /// </summary>
        public static string CoordinateSystemAxisLength {
            get {
                return ResourceManager.GetString("CoordinateSystemAxisLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default materials:.
        /// </summary>
        public static string DefaultMaterials {
            get {
                return ResourceManager.GetString("DefaultMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Coordinate system.
        /// </summary>
        public static string DrawCoordinateSystem {
            get {
                return ResourceManager.GetString("DrawCoordinateSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw fill triangles (Default mode).
        /// </summary>
        public static string DrawFillTriangles {
            get {
                return ResourceManager.GetString("DrawFillTriangles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw sources of lights.
        /// </summary>
        public static string DrawLights {
            get {
                return ResourceManager.GetString("DrawLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Target point.
        /// </summary>
        public static string DrawTargetPoint {
            get {
                return ResourceManager.GetString("DrawTargetPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw vertices of the triangles.
        /// </summary>
        public static string DrawTrianglesVertices {
            get {
                return ResourceManager.GetString("DrawTrianglesVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable lighting.
        /// </summary>
        public static string EnableLightingCheckBoxText {
            get {
                return ResourceManager.GetString("EnableLightingCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Wireframe mode.
        /// </summary>
        public static string EnableWireframeMode {
            get {
                return ResourceManager.GetString("EnableWireframeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of View.
        /// </summary>
        public static string FieldOfView {
            get {
                return ResourceManager.GetString("FieldOfView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Editing.
        /// </summary>
        public static string FinishEditing {
            get {
                return ResourceManager.GetString("FinishEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global material settings.
        /// </summary>
        public static string GlobalMaterialSettings {
            get {
                return ResourceManager.GetString("GlobalMaterialSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid color settings:.
        /// </summary>
        public static string GridColorSettings {
            get {
                return ResourceManager.GetString("GridColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid settings:.
        /// </summary>
        public static string GridSettings {
            get {
                return ResourceManager.GetString("GridSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string GridSpace {
            get {
                return ResourceManager.GetString("GridSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Visibility.
        /// </summary>
        public static string GridVisibility {
            get {
                return ResourceManager.GetString("GridVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolate.
        /// </summary>
        public static string Isolate {
            get {
                return ResourceManager.GetString("Isolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient:.
        /// </summary>
        public static string LightAmbientColor {
            get {
                return ResourceManager.GetString("LightAmbientColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color settings:.
        /// </summary>
        public static string LightColorSettings {
            get {
                return ResourceManager.GetString("LightColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light source diameter.
        /// </summary>
        public static string LightDiameter {
            get {
                return ResourceManager.GetString("LightDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diffuse:.
        /// </summary>
        public static string LightDiffuseColor {
            get {
                return ResourceManager.GetString("LightDiffuseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting settings.
        /// </summary>
        public static string LightingExpanderHeader {
            get {
                return ResourceManager.GetString("LightingExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting.
        /// </summary>
        public static string LightingTabHeader {
            get {
                return ResourceManager.GetString("LightingTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position settings:.
        /// </summary>
        public static string LightPositionSettings {
            get {
                return ResourceManager.GetString("LightPositionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specular:.
        /// </summary>
        public static string LightSpecularColor {
            get {
                return ResourceManager.GetString("LightSpecularColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient:.
        /// </summary>
        public static string MaterialAmbientColor {
            get {
                return ResourceManager.GetString("MaterialAmbientColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diffuse:.
        /// </summary>
        public static string MaterialDiffuseColor {
            get {
                return ResourceManager.GetString("MaterialDiffuseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emission:.
        /// </summary>
        public static string MaterialEmissionColor {
            get {
                return ResourceManager.GetString("MaterialEmissionColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material settings.
        /// </summary>
        public static string MaterialExpanderHeader {
            get {
                return ResourceManager.GetString("MaterialExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specular:.
        /// </summary>
        public static string MaterialSpecularColor {
            get {
                return ResourceManager.GetString("MaterialSpecularColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string MaterialTabHeader {
            get {
                return ResourceManager.GetString("MaterialTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh rendering settings.
        /// </summary>
        public static string MeshRenderingSettings {
            get {
                return ResourceManager.GetString("MeshRenderingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Origin.
        /// </summary>
        public static string MoveToOrigin {
            get {
                return ResourceManager.GetString("MoveToOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orthographic.
        /// </summary>
        public static string OrthographicView {
            get {
                return ResourceManager.GetString("OrthographicView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perspective.
        /// </summary>
        public static string PerspectiveView {
            get {
                return ResourceManager.GetString("PerspectiveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:.
        /// </summary>
        public static string PositionX {
            get {
                return ResourceManager.GetString("PositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y:.
        /// </summary>
        public static string PositionY {
            get {
                return ResourceManager.GetString("PositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z:.
        /// </summary>
        public static string PositionZ {
            get {
                return ResourceManager.GetString("PositionZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection Mode:.
        /// </summary>
        public static string ProjectionMode {
            get {
                return ResourceManager.GetString("ProjectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering.
        /// </summary>
        public static string RenderingTabHeader {
            get {
                return ResourceManager.GetString("RenderingTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default.
        /// </summary>
        public static string RestoreDefaultTransform {
            get {
                return ResourceManager.GetString("RestoreDefaultTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore View.
        /// </summary>
        public static string RestoreView {
            get {
                return ResourceManager.GetString("RestoreView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Around X axis:.
        /// </summary>
        public static string RotationAroundXAxis {
            get {
                return ResourceManager.GetString("RotationAroundXAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Around Y axis:.
        /// </summary>
        public static string RotationAroundYAxis {
            get {
                return ResourceManager.GetString("RotationAroundYAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Around Z axis:.
        /// </summary>
        public static string RotationAroundZAxis {
            get {
                return ResourceManager.GetString("RotationAroundZAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale:.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shininess radius:.
        /// </summary>
        public static string Shininess {
            get {
                return ResourceManager.GetString("Shininess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target point color settings:.
        /// </summary>
        public static string TargetPointColorSettings {
            get {
                return ResourceManager.GetString("TargetPointColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception has been occurred. The application will be terminated.
        /// </summary>
        public static string UnhandledExceptionOccured {
            get {
                return ResourceManager.GetString("UnhandledExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use global material.
        /// </summary>
        public static string UseGlobalMaterial {
            get {
                return ResourceManager.GetString("UseGlobalMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewTabHeader {
            get {
                return ResourceManager.GetString("ViewTabHeader", resourceCulture);
            }
        }
    }
}
