//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colorado.Documents.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Colorado.Documents.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounding box calculation.
        /// </summary>
        internal static string BoundingBoxCalculation {
            get {
                return ResourceManager.GetString("BoundingBoxCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening &quot;{0}&quot; document.
        /// </summary>
        internal static string OpeningDocument {
            get {
                return ResourceManager.GetString("OpeningDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing triangles.
        /// </summary>
        internal static string ProcessingTriangles {
            get {
                return ResourceManager.GetString("ProcessingTriangles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading triangles.
        /// </summary>
        internal static string ReadingTriangles {
            get {
                return ResourceManager.GetString("ReadingTriangles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving &quot;{0}&quot; document
        ///Path to file is &quot;{1}&quot;..
        /// </summary>
        internal static string SavingDocument {
            get {
                return ResourceManager.GetString("SavingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving triangles.
        /// </summary>
        internal static string SavingTriangles {
            get {
                return ResourceManager.GetString("SavingTriangles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertices transformation.
        /// </summary>
        internal static string VerticesTransformation {
            get {
                return ResourceManager.GetString("VerticesTransformation", resourceCulture);
            }
        }
    }
}
